spring:
  servlet:
    multipart:
      max-file-size: 2MB
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    restart:
      enabled: false
  jpa:
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache.mode: UNSPECIFIED

application:
  domain:
    host:
      url: http://localhost:3000
  server:
    host:
      url: http://localhost:8080
  security:
    allowed-origins: http://localhost:3000
    exposed-headers: Authorization
  email:
    sending-address: play.quiz.10@gmail.com
    token:
      validity:
        period: 60
    sending:
      enabled: true

# Trace @Transaction behavior
logging:
  level:
    org:
      springframework: DEBUG
      springframework.transaction:
          interceptor: TRACE
      springframework.security: DEBUG
      springframework.web: DEBUG