application:
  email:
    sending:
      enabled: false

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: TEST_SCHEMA
    password: testpassword
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate.ddl-auto: update
