-- // create_question_sequence
ALTER TABLE Q_QUESTIONS
    ADD CONSTRAINT QUESTIONS_USER_ID
        FOREIGN KEY (ACCOUNT_ID)
            REFERENCES Q_USERS(ACCOUNT_ID)
/execute/

ALTER TABLE Q_QUESTIONS
    ADD CONSTRAINT QUESTIONS_CAT_ID
        FOREIGN KEY (CAT_ID)
            REFERENCES Q_CATEGORIES(CAT_ID)
/execute/


-- //@UNDO
-- SQL to undo the change goes here.
ALTER TABLE Q_QUESTIONS DROP CONSTRAINT QUESTIONS_USER_ID
/execute/
ALTER TABLE Q_QUESTIONS DROP CONSTRAINT QUESTIONS_CAT_ID
/execute/
