-- // create_question_table
CREATE TABLE Q_QUESTIONS (
    QUESTION_ID NUMERIC(20,0) NOT NULL,
    ACCOUNT_ID NUMERIC(20,0) DEFAULT 1 NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    TIP_ID NUMERIC(20,0),
    CAT_ID NUMERIC(20,0) NOT NULL,
    IS_ACTIVE NUMBER(1,0) NOT NULL,
    COMPLEXITY_LEVEL NUMERIC(10,0),
    CONTENT VARCHAR(1000) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    UPDATED_DATE DATE,
    UPDATE_ACCOUNT_ID NUMERIC(20,0),
    TOPIC VARCHAR(200),
    PRIORITY NUMERIC(20,0),
    ATTRIBUTES VARCHAR(500)
)
/execute/

ALTER TABLE Q_QUESTIONS
    ADD CONSTRAINT Q_QUESTIONS_PK
        PRIMARY KEY (QUESTION_ID)
/execute/

-- //@UNDO
DROP TABLE Q_QUESTIONS
/execute/


