-- // create_categories_sequence
ALTER TABLE Q_CATEGORY
    ADD CONSTRAINT SUBCATEGORIES_CATEGORIES_FK
        FOREIGN KEY (SUBCATEGORY_ID)
            REFERENCES Q_CATEGORY(CAT_ID)
            ON DELETE CASCADE
/execute/

ALTER TABLE Q_CATEGORY
    ADD CONSTRAINT NAME_UNIQUE
        UNIQUE (NAME)
/execute/


-- //@UNDO
-- SQL to undo the change goes here.
ALTER TABLE Q_CATEGORY DROP CONSTRAINT SUBCATEGORIES_CATEGORIES_FK
/execute/
ALTER TABLE Q_CATEGORY DROP CONSTRAINT NAME_UNIQUE
/execute/
