-- // create_glossary_sequence
ALTER TABLE Q_GLOSSARIES
    ADD CONSTRAINT GLOSSARY_CATEGORY_FK
        FOREIGN KEY (CAT_ID)
            REFERENCES Q_CATEGORIES(CAT_ID)
/execute/

ALTER TABLE Q_GLOSSARIES
    ADD CONSTRAINT GLOSSARY_PARENT_FK
        FOREIGN KEY (PARENT_ID)
            REFERENCES Q_GLOSSARIES(TERM_ID)
/execute/

ALTER TABLE Q_GLOSSARIES
    ADD CONSTRAINT GLOSSARY_UNIQUE
        UNIQUE (KEY, VALUE, CAT_ID)
/execute/


-- //@UNDO
ALTER TABLE Q_GLOSSARIES DROP CONSTRAINT GLOSSARY_CATEGORY_FK
/execute/
ALTER TABLE Q_GLOSSARIES DROP CONSTRAINT GLOSSARY_PARENT_FK
/execute/
ALTER TABLE Q_GLOSSARIES DROP CONSTRAINT GLOSSARY_UNIQUE
/execute/
