-- // create_users_history_table
ALTER TABLE Q_USER_HISTORY
    ADD CONSTRAINT HISTORY_ACCOUNT_FK
        FOREIGN KEY (ACCOUNT_ID)
            REFERENCES Q_USER(ACCOUNT_ID)
/execute/

ALTER TABLE Q_USER_HISTORY
    ADD CONSTRAINT HISTORY_QUIZ_FK
        FOREIGN KEY (QUIZ_ID)
            REFERENCES Q_QUESTIONZES(QUIZ_ID)
/execute/

-- //@UNDO
-- SQL to undo the change goes here.
ALTER TABLE Q_USER_HISTORY DROP CONSTRAINT HISTORY_ACCOUNT_FK
/execute/
ALTER TABLE Q_USER_HISTORY DROP CONSTRAINT HISTORY_QUIZ_FK
/execute/
