-- // create_user_table
CREATE TABLE Q_USERS_ROLES (
    ACCOUNT_ID NUMERIC(20, 0) REFERENCES Q_USERS(ACCOUNT_ID) ON DELETE CASCADE,
    ROLE_ID NUMERIC(20,0) REFERENCES Q_ROLES(ROLE_ID) ON DELETE CASCADE
)
/execute/

ALTER TABLE Q_USERS_ROLES
    ADD CONSTRAINT Q_USERS_ROLES_PK
        PRIMARY KEY (ACCOUNT_ID, ROLE_ID)
/execute/

-- //@UNDO
DROP TABLE Q_USERS_ROLES
/execute/



