-- // create_users_history_table
ALTER TABLE Q_USER_HISTORIES
    ADD CONSTRAINT HISTORY_ACCOUNT_FK
        FOREIGN KEY (ACCOUNT_ID)
            REFERENCES Q_USERS(ACCOUNT_ID)
/execute/

ALTER TABLE Q_USER_HISTORIES
    ADD CONSTRAINT HISTORY_QUIZ_FK
        FOREIGN KEY (QUIZ_ID)
            REFERENCES Q_QUIZZES(QUIZ_ID)
/execute/

-- //@UNDO
-- SQL to undo the change goes here.
ALTER TABLE Q_USER_HISTORIES DROP CONSTRAINT HISTORY_ACCOUNT_FK
/execute/
ALTER TABLE Q_USER_HISTORIES DROP CONSTRAINT HISTORY_QUIZ_FK
/execute/
