-- // create_glossary_table
CREATE TABLE Q_GLOSSARY (
     TERM_ID NUMERIC(20,0) NOT NULL,
     KEY VARCHAR(100) NOT NULL,
     VALUE VARCHAR(100),
     CAT_ID NUMERIC(20,0) NOT NULL,
     TYPE_ID NUMERIC(20,0),
     ATTACHMENT BLOB,
     OPTIONS VARCHAR(100),
     PARENT_ID NUMERIC(20,0) DEFAULT NULL,
     IS_ACTIVE NUMBER(1,0) DEFAULT 0 NOT NULL,
     CREATED_BY NUMERIC(20, 0),
     UPDATED_BY NUMERIC(20, 0),
     CREATED_DATE DATE NOT NULL,
     UPDATED_DATE DATE
)
/execute/

ALTER TABLE Q_GLOSSARY
    ADD CONSTRAINT Q_GLOSSARY_PK
        PRIMARY KEY (TERM_ID)
/execute/

-- //@UNDO
DROP TABLE Q_GLOSSARY
/execute/


