-- // create_verification_tokens
CREATE TABLE Q_VERIFICATION_TOKEN (
    TOKEN_ID NUMERIC(20,0) NOT NULL,
    ACCOUNT_ID NUMERIC(20,0) NOT NULL,
    TOKEN VARCHAR(120),
    ISSUED_DATE DATE NOT NULL,
    VALIDITY_PERIOD NUMBER,
    ACTIVATION_DATE DATE
)
/execute/

ALTER TABLE Q_VERIFICATION_TOKEN
    ADD CONSTRAINT Q_VERIFICATION_TOKEN_PK
        PRIMARY KEY (TOKEN_ID)
/execute/

ALTER TABLE Q_VERIFICATION_TOKEN
    ADD CONSTRAINT Q_USER_Q_VT_FK
        FOREIGN KEY (ACCOUNT_ID)
            REFERENCES Q_USER(ACCOUNT_ID)
            ON DELETE CASCADE
/execute/

-- //@UNDO
DROP TABLE Q_VERIFICATION_TOKEN
/execute/


