-- // create_question_sequence
ALTER TABLE Q_QUESTION
    ADD CONSTRAINT QUESTIONS_USER_ID
        FOREIGN KEY (ACCOUNT_ID)
            REFERENCES Q_USER(ACCOUNT_ID)
/execute/

ALTER TABLE Q_QUESTION
    ADD CONSTRAINT QUESTIONS_CAT_ID
        FOREIGN KEY (CAT_ID)
            REFERENCES Q_CATEGORY(CAT_ID)
/execute/


-- //@UNDO
-- SQL to undo the change goes here.
ALTER TABLE Q_QUESTION DROP CONSTRAINT QUESTIONS_USER_ID
/execute/
ALTER TABLE Q_QUESTION DROP CONSTRAINT QUESTIONS_CAT_ID
/execute/
