-- // create_answer_sequence
ALTER TABLE Q_ANSWERS
    ADD CONSTRAINT ANSWERS_QUESTIONS_FK
        FOREIGN KEY (QUESTION_ID)
            REFERENCES Q_QUESTIONS(QUESTION_ID)
            ON DELETE CASCADE
/execute/

ALTER TABLE Q_ANSWERS
    ADD CONSTRAINT ANSWERS_GLOSSARIES_FK
        FOREIGN KEY (TERM_ID)
            REFERENCES Q_GLOSSARIES(TERM_ID)
/execute/


-- //@UNDO
-- SQL to undo the change goes here.
ALTER TABLE Q_ANSWERS DROP CONSTRAINT ANSWERS_QUESTIONS_FK
/execute/
ALTER TABLE Q_ANSWERS DROP CONSTRAINT ANSWERS_GLOSSARIES_FK
/execute/


