-- // create_verification_tokens
CREATE TABLE Q_VERIFICATION_TOKENS (
    TOKEN_ID NUMERIC(20,0) NOT NULL,
    ACCOUNT_ID NUMERIC(20,0) NOT NULL,
    TOKEN VARCHAR(120),
    ISSUED_DATE DATE NOT NULL,
    VALIDITY_PERIOD NUMBER,
    ACTIVATION_DATE DATE
)
/execute/

ALTER TABLE Q_VERIFICATION_TOKENS
    ADD CONSTRAINT Q_VERIFICATION_TOKENS_PK
        PRIMARY KEY (TOKEN_ID)
/execute/

ALTER TABLE Q_VERIFICATION_TOKENS
    ADD CONSTRAINT Q_USERS_Q_VT_FK
        FOREIGN KEY (ACCOUNT_ID)
            REFERENCES Q_USERS(ACCOUNT_ID)
            ON DELETE CASCADE
/execute/

-- //@UNDO
DROP TABLE Q_VERIFICATION_TOKENS
/execute/


