-- // create_glossary_sequence
ALTER TABLE Q_GLOSSARY
    ADD CONSTRAINT GLOSSARY_CATEGORY_FK
        FOREIGN KEY (CAT_ID)
            REFERENCES Q_CATEGORY(CAT_ID)
/execute/

ALTER TABLE Q_GLOSSARY
    ADD CONSTRAINT GLOSSARY_PARENT_FK
        FOREIGN KEY (PARENT_ID)
            REFERENCES Q_GLOSSARY(TERM_ID)
/execute/

ALTER TABLE Q_GLOSSARY
    ADD CONSTRAINT GLOSSARY_UNIQUE
        UNIQUE (KEY, VALUE, CAT_ID)
/execute/

ALTER TABLE Q_GLOSSARY
    ADD CONSTRAINT GLOSSARY_TYPE_FK
        FOREIGN KEY (TYPE_ID)
            REFERENCES Q_GLOSSARY_TYPE(ID)
/execute/


-- //@UNDO
ALTER TABLE Q_GLOSSARY DROP CONSTRAINT GLOSSARY_CATEGORY_FK
/execute/
ALTER TABLE Q_GLOSSARY DROP CONSTRAINT GLOSSARY_PARENT_FK
/execute/
ALTER TABLE Q_GLOSSARY DROP CONSTRAINT GLOSSARY_UNIQUE
/execute/
