-- // create_answer_table
CREATE TABLE Q_ANSWERS (
    ANS_ID NUMERIC(20,0) NOT NULL,
    QUESTION_ID NUMERIC(20,0) NOT NULL,
    CONTENT VARCHAR(1000) NOT NULL,
    TERM_ID NUMERIC(20,0) DEFAULT NULL
)
/execute/

ALTER TABLE Q_ANSWERS
    ADD CONSTRAINT Q_ANSWERS_PK
        PRIMARY KEY (ANS_ID)
/execute/

-- //@UNDO
DROP TABLE Q_ANSWERS
/execute/


