-- // create_property_table
CREATE TABLE Q_PROPERTY (
    PROPERTY_ID NUMERIC(20,0) NOT NULL,
    NAME VARCHAR(1000) NOT NULL,
    VALUE VARCHAR(800) NOT NULL,
    OLD_VALUE VARCHAR(800),
    CREATED_BY NUMERIC(20, 0),
    UPDATED_BY NUMERIC(20, 0),
    CREATED_DATE DATE NOT NULL,
    UPDATED_DATE DATE
)
/execute/

ALTER TABLE Q_PROPERTY
    ADD CONSTRAINT Q_PROPERTY_PK
        PRIMARY KEY (PROPERTY_ID)
/execute/

-- //@UNDO
DROP TABLE Q_PROPERTY
/execute/

