-- // create_glossary_table
CREATE TABLE Q_GLOSSARIES (
     TERM_ID NUMERIC(20,0) NOT NULL,
     KEY VARCHAR(100) NOT NULL,
     VALUE VARCHAR(100),
     CAT_ID NUMERIC(20,0) NOT NULL,
     ATTACHMENT BLOB,
     OPTIONS VARCHAR(100),
     PARENT_ID NUMERIC(20,0) DEFAULT NULL,
     IS_ACTIVE NUMBER(1,0) DEFAULT 0 NOT NULL
)
/execute/

ALTER TABLE Q_GLOSSARIES
    ADD CONSTRAINT Q_GLOSSARIES_PK
        PRIMARY KEY (TERM_ID)
/execute/

-- //@UNDO
DROP TABLE Q_GLOSSARIES
/execute/


