-- // create_categories_table
CREATE TABLE Q_CATEGORIES (
     CAT_ID NUMERIC(20,0) NOT NULL,
     NAME VARCHAR(150),
     NATURAL_ID VARCHAR(150) NOT NULL,
     SUBCATEGORY_ID NUMERIC(20,0) DEFAULT NULL
)
/execute/

ALTER TABLE Q_CATEGORIES
    ADD CONSTRAINT Q_CATEGORIES_PK
        PRIMARY KEY (CAT_ID)
/execute/

-- //@UNDO
-- SQL to undo the change goes here.
DROP TABLE Q_CATEGORIES
/execute/


