-- // create_question_table
CREATE TABLE Q_QUESTION (
    QUESTION_ID NUMERIC(20,0) NOT NULL,
    ACCOUNT_ID NUMERIC(20,0) DEFAULT 1 NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    TIP_ID NUMERIC(20,0),
    CAT_ID NUMERIC(20,0) NOT NULL,
    IS_ACTIVE NUMBER(1,0) NOT NULL,
    COMPLEXITY_LEVEL NUMERIC(10,0),
    CONTENT VARCHAR(1000) NOT NULL,
    TOPIC VARCHAR(200),
    PRIORITY NUMERIC(20,0),
    ATTRIBUTES VARCHAR(500),
    CREATED_BY NUMERIC(20, 0),
    UPDATED_BY NUMERIC(20, 0),
    CREATED_DATE DATE NOT NULL,
    UPDATED_DATE DATE
)
/execute/

ALTER TABLE Q_QUESTION
    ADD CONSTRAINT Q_QUESTION_PK
        PRIMARY KEY (QUESTION_ID)
/execute/

-- //@UNDO
DROP TABLE Q_QUESTION
/execute/


