-- // name_of_the_migration
INSERT INTO Q_CATEGORIES VALUES (1, 'Express', 'EXPRESS', null, 0)/execute/

INSERT INTO Q_PROPERTIES VALUES (1, 'DEFAULT_EXPRESS_QUESTIONS_COUNT', 10, null)/execute/
INSERT INTO Q_PROPERTIES VALUES (2, 'EXPRESS_QUIZ_DEFAULT_ANSWER_COUNT', 4, null)/execute/
INSERT INTO Q_PROPERTIES VALUES (3, 'ENCRYPTION_SECRET_KEY', '2Fq-GH0m45l-o=27$aaOE9@j', null)/execute/
INSERT INTO Q_PROPERTIES VALUES (4, 'ENCRYPTION_ALGORITHM', 'AES/ECB/PKCS5Padding', null)/execute/
INSERT INTO Q_PROPERTIES VALUES (5, 'EXPRESS_QUIZ_DEFAULT_TIME_SECONDS', '100', null)/execute/

-- //@UNDO
DELETE FROM Q_CATEGORIES WHERE CAT_ID = 1/execute/

DELETE FROM Q_PROPERTIES WHERE PROPERTY_ID = 1/execute/
DELETE FROM Q_PROPERTIES WHERE PROPERTY_ID = 2/execute/
DELETE FROM Q_PROPERTIES WHERE PROPERTY_ID = 3/execute/
DELETE FROM Q_PROPERTIES WHERE PROPERTY_ID = 4/execute/
DELETE FROM Q_PROPERTIES WHERE PROPERTY_ID = 5/execute/
