-- // create_message_table
CREATE TABLE Q_MESSAGE (
    MSG_ID NUMERIC(20,0) NOT NULL,
    CONTENT VARCHAR(800),
    SOURCE VARCHAR(100),
    DESTINATION VARCHAR(100),
    SESSION_ID VARCHAR(20),
    ATTACHMENT BLOB,
    CREATED_BY NUMERIC(20, 0),
    UPDATED_BY NUMERIC(20, 0),
    CREATED_DATE DATE NOT NULL,
    UPDATED_DATE DATE
)
/execute/

ALTER TABLE Q_MESSAGE
    ADD CONSTRAINT MSG_ID_PK
        PRIMARY KEY (MSG_ID)
    /execute/

-- //@UNDO
DROP TABLE Q_MESSAGE
/execute/



