-- // add_express_constants
INSERT INTO Q_CATEGORY VALUES (1, 'Express', 'EXPRESS', null, null, 0)/execute/

INSERT INTO Q_PROPERTY VALUES (1, 'DEFAULT_EXPRESS_QUESTIONS_COUNT', 10, null)/execute/
INSERT INTO Q_PROPERTY VALUES (2, 'EXPRESS_QUIZ_DEFAULT_OPTIONS_COUNT', 4, null)/execute/
INSERT INTO Q_PROPERTY VALUES (3, 'ENCRYPTION_SECRET_KEY', '2Fq-GH0m45l-o=27$aaOE9@j', null)/execute/
INSERT INTO Q_PROPERTY VALUES (4, 'ENCRYPTION_ALGORITHM', 'AES/ECB/PKCS5Padding', null)/execute/
INSERT INTO Q_PROPERTY VALUES (5, 'EXPRESS_QUIZ_DEFAULT_TIME_SECONDS', '100', null)/execute/
INSERT INTO Q_PROPERTY VALUES (6, 'DEFAULT_QUIZ_QUESTIONS_COUNT', '20', null)/execute/

-- //@UNDO
DELETE FROM Q_USER_HISTORY WHERE 1 = 1/execute/
DELETE FROM Q_QUIZ WHERE 1 = 1/execute/
DELETE FROM Q_CATEGORY WHERE CAT_ID = 1/execute/

DELETE FROM Q_PROPERTY WHERE PROPERTY_ID = 1/execute/
DELETE FROM Q_PROPERTY WHERE PROPERTY_ID = 2/execute/
DELETE FROM Q_PROPERTY WHERE PROPERTY_ID = 3/execute/
DELETE FROM Q_PROPERTY WHERE PROPERTY_ID = 4/execute/
DELETE FROM Q_PROPERTY WHERE PROPERTY_ID = 5/execute/
DELETE FROM Q_PROPERTY WHERE PROPERTY_ID = 6/execute/
