-- // create_category_translations_constraints
ALTER TABLE Q_KNOWLEDGE_BASE
    ADD CONSTRAINT KNOWLEDGE_BASE_CATEGORY_FK
        FOREIGN KEY (CAT_ID)
            REFERENCES Q_CATEGORY(CAT_ID)
/execute/

ALTER TABLE Q_KNOWLEDGE_BASE
    ADD CONSTRAINT KNOWLEDGE_BASE_PARENT_FK
        FOREIGN KEY (PARENT_ID)
            REFERENCES Q_KNOWLEDGE_BASE(ID)
/execute/

-- //@UNDO
ALTER TABLE Q_KNOWLEDGE_BASE DROP CONSTRAINT KNOWLEDGE_BASE_CATEGORY_FK
/execute/
ALTER TABLE Q_KNOWLEDGE_BASE DROP CONSTRAINT KNOWLEDGE_BASE_PARENT_FK
/execute/
