-- // create_user_table
CREATE TABLE Q_USER_OCCUPATION (
                              ACCOUNT_ID NUMERIC(20, 0) REFERENCES Q_USER(ACCOUNT_ID) ON DELETE CASCADE,
                              OCCUPATION_ID NUMERIC(20,0) REFERENCES Q_OCCUPATION(ID) ON DELETE CASCADE
)
/execute/

ALTER TABLE Q_USER_OCCUPATION
    ADD CONSTRAINT Q_USER_OCCUPATION_PK
        PRIMARY KEY (ACCOUNT_ID, OCCUPATION_ID)
/execute/

-- //@UNDO
DROP TABLE Q_USER_OCCUPATION
/execute/



