-- CREATE USER gnosis IDENTIFIED BY admin;
-- -- Grant DBA (Database Administrator) role
-- GRANT DBA TO gnosis;
--
-- -- Alternatively, you can grant individual privileges as needed, for example:
-- GRANT CREATE SESSION TO gnosis;
-- GRANT CREATE TABLE TO gnosis;
-- GRANT CREATE VIEW TO gnosis;
--
-- ALTER USER gnosis ACCOUNT UNLOCK;
-- ALTER USER gnosis TEMPORARY TABLESPACE temp;
-- ALTER USER gnosis PROFILE DEFAULT;
-- GRANT CREATE SESSION TO gnosis;
--
