INSERT INTO TEST_SCHEMA.Q_CATEGORY
(CAT_ID, NAME, NATURAL_ID, SUBCATEGORY_ID, VISIBLE)
VALUES(2, 'Earth', 'EARTH', NULL, 1);

INSERT INTO TEST_SCHEMA.Q_CATEGORY
(CAT_ID, NAME, NATURAL_ID, SUBCATEGORY_ID, VISIBLE)
VALUES(3, 'Continent', 'CONTINENT', 2, 1);
